name = "quantus_technik"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# DO NOT set "main" â€” Cloudflare auto-detects Next.js now

[build]
command = "npm run build"

[site]
bucket = ".next"
